name: thepublictransport_app
description: Die ÖPV App für Deutschland
version: 0.0.7+7
author: Tristan Marsell, The Public Transport

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.2.0
  desiredrive_api_flutter:
    path: ./desiredrive_api_flutter
  trustdatabase_flutter_api:
    path: ./trustdatabase_flutter_api
  http: ^0.12.0+1
  permission_handler: 3.0.0
  flutter_svg: 0.12.4
  gradient_widgets: 0.4.1
  outline_material_icons: 0.1.0
  bubble_bottom_bar: 1.2.0
  url_launcher: 5.0.2
  auto_size_text: 1.1.2
  flutter_typeahead: 1.5.0
  frideos_light: 0.4.3
  flutter_inner_drawer: 0.2.6
  shared_preferences: 0.5.2
  sliding_up_panel: ^0.3.4
  timeline_list: ^0.0.3
  liquid_pull_to_refresh: ^1.1.0
  preferences: ^3.0.0
  transformer_page_view: 0.1.6
  eva_icons_flutter: 1.0.4
  package_info: ^0.4.0+3
  flutter_spinkit: 3.1.0
  flare_flutter: 1.5.1
  sprung: 1.1.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - fonts/
    - vectors/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
